### ISSUE TITLE
genes without name/Ensembl ID

### ISSUE THREAD

**Issue by sjcarmona** [carmonalab/SignatuR#3]
Multiple genes without Ensembl ID (eg IFNR, IRF8)
x <- GetSignature(SignatuR$Hs)
> x$IFN[names(x$IFN)==""]
                    
   "IFNR" "PRKRAP1"

**Comment by p-gueguen** [comment]
That's a good catch. Some genes are indeed identified by HGNC but were not mapped yet to the genome. cf https://www.ncbi.nlm.nih.gov/gene/3466 for IFNR for instance, where the gene is 'not in current annotation release'. 

There is no RefSeq mapping for these genes, as compared to IL7R for example: https://www.ncbi.nlm.nih.gov/gene/3575

Should we discard all genes that do not have ENS names? As we mainly use `GetSignature(SignatuR$Hs)` to discard genes from HVGs, maybe we should keep the maximum of genes in the SignatuR lists, as some of these genes are indeed expressed in our single-cell datasets (but not a lot as you can see on the plot below).
![image](https://user-images.githubusercontent.com/34238952/183626212-b1298079-0e6e-45a1-ac4b-3e9ee59e3acc.png)

**Comment by p-gueguen** [comment]
Out of simplicity, I removed the gene names from SignatuR database that didn't have any ENSEMBL identifier. As shown above, the impact should be very minimal.
