### ISSUE TITLE
Homogenize SignatuR data.tree for Human and Mouse

### ISSUE THREAD

**Issue by JGarnica22** [carmonalab/SignatuR#4]
Database categories are differently organized in mouse and human (i.e. HeatShock (Mm) in Programs, while HSP (Hs) in block list)

Some signature names differ between human and mouse (i.e. IFN (Hs) vs  IfnResp (Mm), HSP (Hs) vs HeatShock (Mm))

**Comment by mass-a** [comment]
The structure now is more consistent between the two species (also added pseudo-genes, non-coding genes and immunoglobulins for mouse):


<img width="1073" alt="Screenshot 2024-03-28 at 12 46 56" src="https://github.com/carmonalab/SignatuR/assets/56030596/d1951baa-590f-4729-a332-1951091f61d1">
